# tasks file
---

- name: Tarefas para '{{ ansible_distribution|lower }}'
  include_tasks: '{{ ansible_distribution|lower }}.yml'

- name: Instalando Pre-requisitos
  package:
    name: '{{ item }}'
    state: present
  loop:
  - vim
  - vim-powerline
  - git
  - curl
  - zsh
  - code
  - guake
  - remmina
  - remmina-plugins-rdp
  - brave-browser
  - vagrant
  - tmux
  - flameshot
  - locate
  - python3-firewall
  - vlc
  - python-vlc
  - python2
  - python-firewall
  - openssh-server
  - NetworkManager
  - vagrant-libvirt

- name: Instalando pacotes Virtualização KVM
  package:
    name: '{{ item }}'
    state: present
  loop:
  - qemu-kvm 
  - libvirt 
  - virt-install 
  - bridge-utils

- name: Liberando portas Firewalld
  command: firewall-cmd --zone=public --add-service={{ item }} --permanent
  loop:
  - cockpit
  - ssh

- name: Liberando portas Firewalld
  command: firewall-cmd --zone=public --add-service={{ item }}
  loop:
  - cockpit
  - ssh

- name: Instalando pacotes adicionais Virtualização KVM
  package:
    name: '{{ item }}'
    state: present
  loop:
  - virt-manager
  - libvirt-devel 
  - virt-top 
  - libguestfs-tools 
  - guestfs-tools
  - cockpit
  - cockpit-machines
  - cockpit-networkmanager
  - cockpit-selinux

- name: Habilitando serviços na inicialização
  systemd:
    name: '{{ item }}'
    state: started
    enabled: yes
  loop:
  - libvirtd
  - cockpit

- name: Desabilitando SELinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  register: selinuxdisabled

- name: Aguardando 5 Segundos para Reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: selinuxdisabled is changed